blank_issues_enabled: true
contact_links:
  - name: Something else?
    url: https://github.com/dexisapp/dexis/discussions
    about: Feel free to ask and answer questions over in GitHub Discussions
  - name: Dexis Community Support
    url: dexis.app
    about: Dexis Community - a place to ask, learn and engage with others
